### ISSUE TITLE
Can I have a config file for Tevo Tarantula with small bed and SN04-N please?

### ISSUE THREAD

**Issue by senadaruc** [JimBrown/MarlinTarantula#4]
Hi Jim,

Can I have a config file for Tevo Tarantula with a small bed and SN04-N please?

Thanks,

**Comment by JimBrown** [comment]
Wish I could help, but I can't do config files for stuff I don't have. I'm relying on others to send me working config files for the stuff they have so that I can add them to the example configs. If you do manage to get your setup working, feel free to send me the config files so I can add them for others. Thanks!
