### ISSUE TITLE
X Limit Switch is ignored while homing X Axis

### ISSUE THREAD

**Issue by itsurboibrad** [JimBrown/MarlinTarantula#40]
Bug Report
Description:
When homing the Axis the X axis limit switch is ignored. This behavior can be observed when using the Auto Home and Home X axis specifically. The Y axis and the Z axis operate normally.

Expected behavior:
When running the homing script the X-Limit switch should trigger the Marlin Firmware to stop at the edge of the metal beam.

Actual Behavior:
The X-carriage on the X-Axis hits the edge and the motor keeps trying to move it. A grinding noise occurs.

Steps to Reproduce:
Menu -> Prepare -> Auto Home/Home X

**Comment by JimBrown** [comment]
Not a bug. Most likely your X axis endstop switch is not working due to a broken wire, or not plugged in to the correct connector on the board. Connect your printer to your computer via USB. Use a host program such as Pronterface to send M119 to the printer. All axis should show "open". Press and hold the X axis endstop switch with your finger and send M119 again. The X axis should show "triggered". If it does not, then it is not working.
