### ISSUE TITLE
manual bed-leveling values cleared after printer powered off

### ISSUE THREAD

**Issue by rjl9** [JimBrown/MarlinTarantula#47]
Hello,

I think I may have run into a bug but wanted to get verification of functionality in case it is wrong doing on my part. 

I run my manual bed leveling on my tevo tarantula and store my settings from the bed leveling menu. I run my print and everything works great. After a power down of the printer, I try to reprint the same gcode and my bed leveling settings have been cleared. I go into the bed leveling menu and load settings and it does it beep and says load complete. I run the print again but my setting are not restored to the saved bed leveling i had done before the power off. I have also bed leveled, stored the settings and then store to eeprom and have not been able to regain my leveling settings after a reboot that way either. 

I am not sure if this a bug or acting as expected. I there a way around storing the results of your mesh leveling until you run leveling again even if the printer goes through a power cycle? Or is it expected to run the manual bed leveling before every print?

**Comment by JimBrown** [comment]
Sorry for the delay responding, was out of town.

You certainly should be able to store and retrieve your bed leveling mesh. I believe there are certain steps you have to implement to get it to work. But, since I don't use manual mesh bed leveling, I don't really know what those steps are. Best be would be to ask your question on the FB group.

Good luck!
