### ISSUE TITLE
EXPERIMENTAL_SCURVE should be enabled by default

### ISSUE THREAD

**Issue by 201303998** [JimBrown/MarlinTarantula#76]
Compiling error. 
S_CURVE_ACCELERATION is enabled by default in Configuration.h
EXPERIMENTAL_SCURVE is disabled by default in Configuration_adv.h. 
Sanity check asks one to enable EXPERIMENTAL_SCURVE, which makes it work.

**Comment by JimBrown** [comment]
S_CURVE_ACCELERATION is NOT enabled by default in configuration.h

However, if you do enable it you will get the sanity check error mentioned above.

This is because LIN_ADVANCE IS enabled by default in configuration_adv.h. If both LIN_ADVANCE and S_CURVE_ACCELERATION are enabled, then EXPERIMENTAL_SCURVE is required.

However, it is noted that LIN_ADVANCE and S_CURVE_ACCELERATION do not play well together. Therefore I have updated the EasyConfig section to include the ability to enable either or both LIN_ADVANCE and S_CURVE_ACCELERATION, and if both are enabled, EXPERIMENTAL_SCURVE is also enabled.

Thanks for bringing this to my attention.
